# Generated by Django 3.0.6 on 2020-05-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=127)),
                ('username', models.CharField(max_length=63)),
                ('gender', models.CharField(choices=[('남', '남성'), ('여', '여성')], max_length=15)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
