# Generated by Django 3.0.6 on 2020-05-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'ordering': ['id']},
        ),
    ]
