# Generated by Django 3.0.6 on 2020-05-24 11:45

from django.db import migrations, models
import toy_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('toy_api', '0002_auto_20200524_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, validators=[toy_api.models.min_length_3_validator]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('남', '남성'), ('여', '여성')], max_length=15, validators=[toy_api.models.gender_validator]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=127, validators=[toy_api.models.min_length_3_validator]),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=63, validators=[toy_api.models.min_length_3_validator]),
        ),
    ]
